<a href="https://colab.research.google.com/github/harishkaparwan/GettingStartedWithPython/blob/main/part2/notebook/Playground_FileReadWrite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#rt to read a text file. 
#wt to write a file
#'rb'
#wb
# open('somefile.txt', 'rt', encoding='latin-1') as f:

# Read the entire file as a single string
with open('/Users/harishkaparwan/Developer/Github/GettingStartedWithPython/hck.txt', 'rt') as f: 
        data = f.read()
        print(data)

# Iterate over the lines of the file
with open('/Users/harishkaparwan/Developer/Github/GettingStartedWithPython/hck.txt', 'rt') as f: 
    for line in f:
        print(line)
       
        
# Redirected print statement
with open('/Users/harishkaparwan/Developer/Github/GettingStartedWithPython/hck.txt', 'wt') as f: 
    print("This i smy new", file=f)
    print("This i smy new 4", file=f)
        
# Iterate over the lines of the file
with open('/Users/harishkaparwan/Developer/Github/GettingStartedWithPython/hck.txt', 'rt') as f: 
    for line in f:
        print(line)

This i smy new
This i smy new 3

This i smy new

This i smy new 3

This i smy new

This i smy new 4

In [ ]:
import array
nums = array.array('i', [1, 2, 3, 4]) 
with open('/Users/harishkaparwan/Developer/Github/GettingStartedWithPython/hckdata.bin','wb') as f:
        f.write(nums)
        f.close()

In [ ]:
with open('/Users/harishkaparwan/Developer/Github/GettingStartedWithPython/hckdata.bin', 'rb') as f: 
    f.readinto(a)
    print(a)

array('i', [1, 2, 3, 4, 0, 0, 0, 0])

In [ ]:
import os
if not os.path.exists('/Users/harishkaparwan/Developer/Github/GettingStartedWithPython/hckdata.bin'): 
        print('File already exists!')
else:
    print('File already exists!')

File already exists!

In [ ]:
 # gzip compression
import gzip
with gzip.open('somefile.gz', 'rt') as f:
        text = f.read()
    # bz2 compression
import bz2
with bz2.open('somefile.bz2', 'rt') as f:
text = f.read()
Similarly, to write compressed data, do this:
    # gzip compression
import gzip
with gzip.open('somefile.gz', 'wt') as f:
        f.write(text)
    # bz2 compression
import bz2
with bz2.open('somefile.bz2', 'wt') as f:
f.write(text)

In [ ]:
#Serializing Python Objects
#The most common approach for serializing data is to use the pickle module. To dump an object to a file, you do this:
import pickle
data = ... # Some Python object 
f = open('somefile', 'wb')
pickle.dump(data, f)

#To dump an object to a string use pickle dumps
s = pickle.dumps(data)
#To re-create an object from a byte stream, use either the pickle.load() or pick le.loads() functions. For example:

# Restore from a file
f = open('somefile', 'rb')
data = pickle.load(f)

# Restore from a string
data = pickle.loads(s)

In [ ]:
import csv
with open('/Users/harishkaparwan/Developer/Github/GettingStartedWithPython/stocks.csv') as f:
    f_csv = csv.reader(f) 
    headers = next(f_csv) 
    for row in f_csv:
        print(row)

['MSFT', 'Jan 1 2000', '39.81']
['MSFT', 'Feb 1 2000', '36.35']
['MSFT', 'Mar 1 2000', '43.22']
['MSFT', 'Apr 1 2000', '28.37']
['MSFT', 'May 1 2000', '25.45']
['MSFT', 'Jun 1 2000', '32.54']
['MSFT', 'Jul 1 2000', '28.4']
['MSFT', 'Aug 1 2000', '28.4']
['MSFT', 'Sep 1 2000', '24.53']
['MSFT', 'Oct 1 2000', '28.02']
['MSFT', 'Nov 1 2000', '23.34']
['MSFT', 'Dec 1 2000', '17.65']
['MSFT', 'Jan 1 2001', '24.84']
['MSFT', 'Feb 1 2001', '24']
['MSFT', 'Mar 1 2001', '22.25']
['MSFT', 'Apr 1 2001', '27.56']
['MSFT', 'May 1 2001', '28.14']
['MSFT', 'Jun 1 2001', '29.7']
['MSFT', 'Jul 1 2001', '26.93']
['MSFT', 'Aug 1 2001', '23.21']
['MSFT', 'Sep 1 2001', '20.82']
['MSFT', 'Oct 1 2001', '23.65']
['MSFT', 'Nov 1 2001', '26.12']
['MSFT', 'Dec 1 2001', '26.95']
['MSFT', 'Jan 1 2002', '25.92']
['MSFT', 'Feb 1 2002', '23.73']
['MSFT', 'Mar 1 2002', '24.53']
['MSFT', 'Apr 1 2002', '21.26']
['MSFT', 'May 1 2002', '20.71']
['MSFT', 'Jun 1 2002', '22.25']
['MSFT', 'Jul 1 2002', '19.52']
['MSFT', 'Aug 1 2002', '19.97']
['MSFT', 'Sep 1 2002', '17.79']
['MSFT', 'Oct 1 2002', '21.75']
['MSFT', 'Nov 1 2002', '23.46']
['MSFT', 'Dec 1 2002', '21.03']
['MSFT', 'Jan 1 2003', '19.31']
['MSFT', 'Feb 1 2003', '19.34']
['MSFT', 'Mar 1 2003', '19.76']
['MSFT', 'Apr 1 2003', '20.87']
['MSFT', 'May 1 2003', '20.09']
['MSFT', 'Jun 1 2003', '20.93']
['MSFT', 'Jul 1 2003', '21.56']
['MSFT', 'Aug 1 2003', '21.65']
['MSFT', 'Sep 1 2003', '22.69']
['MSFT', 'Oct 1 2003', '21.45']
['MSFT', 'Nov 1 2003', '21.1']
['MSFT', 'Dec 1 2003', '22.46']
['MSFT', 'Jan 1 2004', '22.69']
['MSFT', 'Feb 1 2004', '21.77']
['MSFT', 'Mar 1 2004', '20.46']
['MSFT', 'Apr 1 2004', '21.45']
['MSFT', 'May 1 2004', '21.53']
['MSFT', 'Jun 1 2004', '23.44']
['MSFT', 'Jul 1 2004', '23.38']
['MSFT', 'Aug 1 2004', '22.47']
['MSFT', 'Sep 1 2004', '22.76']
['MSFT', 'Oct 1 2004', '23.02']
['MSFT', 'Nov 1 2004', '24.6']
['MSFT', 'Dec 1 2004', '24.52']
['MSFT', 'Jan 1 2005', '24.11']
['MSFT', 'Feb 1 2005', '23.15']
['MSFT', 'Mar 1 2005', '22.24']
['MSFT', 'Apr 1 2005', '23.28']
['MSFT', 'May 1 2005', '23.82']
['MSFT', 'Jun 1 2005', '22.93']
['MSFT', 'Jul 1 2005', '23.64']
['MSFT', 'Aug 1 2005', '25.35']
['MSFT', 'Sep 1 2005', '23.83']
['MSFT', 'Oct 1 2005', '23.8']
['MSFT', 'Nov 1 2005', '25.71']
['MSFT', 'Dec 1 2005', '24.29']
['MSFT', 'Jan 1 2006', '26.14']
['MSFT', 'Feb 1 2006', '25.04']
['MSFT', 'Mar 1 2006', '25.36']
['MSFT', 'Apr 1 2006', '22.5']
['MSFT', 'May 1 2006', '21.19']
['MSFT', 'Jun 1 2006', '21.8']
['MSFT', 'Jul 1 2006', '22.51']
['MSFT', 'Aug 1 2006', '24.13']
['MSFT', 'Sep 1 2006', '25.68']
['MSFT', 'Oct 1 2006', '26.96']
['MSFT', 'Nov 1 2006', '27.66']
['MSFT', 'Dec 1 2006', '28.13']
['MSFT', 'Jan 1 2007', '29.07']
['MSFT', 'Feb 1 2007', '26.63']
['MSFT', 'Mar 1 2007', '26.35']
['MSFT', 'Apr 1 2007', '28.3']
['MSFT', 'May 1 2007', '29.11']
['MSFT', 'Jun 1 2007', '27.95']
['MSFT', 'Jul 1 2007', '27.5']
['MSFT', 'Aug 1 2007', '27.34']
['MSFT', 'Sep 1 2007', '28.04']
['MSFT', 'Oct 1 2007', '35.03']
['MSFT', 'Nov 1 2007', '32.09']
['MSFT', 'Dec 1 2007', '34']
['MSFT', 'Jan 1 2008', '31.13']
['MSFT', 'Feb 1 2008', '26.07']
['MSFT', 'Mar 1 2008', '27.21']
['MSFT', 'Apr 1 2008', '27.34']
['MSFT', 'May 1 2008', '27.25']
['MSFT', 'Jun 1 2008', '26.47']
['MSFT', 'Jul 1 2008', '24.75']
['MSFT', 'Aug 1 2008', '26.36']
['MSFT', 'Sep 1 2008', '25.78']
['MSFT', 'Oct 1 2008', '21.57']
['MSFT', 'Nov 1 2008', '19.66']
['MSFT', 'Dec 1 2008', '18.91']
['MSFT', 'Jan 1 2009', '16.63']
['MSFT', 'Feb 1 2009', '15.81']
['MSFT', 'Mar 1 2009', '17.99']
['MSFT', 'Apr 1 2009', '19.84']
['MSFT', 'May 1 2009', '20.59']
['MSFT', 'Jun 1 2009', '23.42']
['MSFT', 'Jul 1 2009', '23.18']
['MSFT', 'Aug 1 2009', '24.43']
['MSFT', 'Sep 1 2009', '25.49']
['MSFT', 'Oct 1 2009', '27.48']
['MSFT', 'Nov 1 2009', '29.27']
['MSFT', 'Dec 1 2009', '30.34']
['MSFT', 'Jan 1 2010', '28.05']
['MSFT', 'Feb 1 2010', '28.67']
['MSFT', 'Mar 1 2010', '28.8']
['AMZN', 'Jan 1 2000', '64.56']
['AMZN', 'Feb 1 2000', '68.87']
['AMZN', 'Mar 1 2000', '67']
['AMZN', 'Apr 1 2000', '55.19']
['AMZN', 'May 1 2000', '48.31']
['AMZN', 'Jun 1 2000', '36.31']
['AMZN', 'Jul 1 2000', '30.12']
['AMZN', 'Aug 1 2000', '41.5']
['AMZN', 'Sep 1 2000', '38.44']
['AMZN', 'Oct 1 2000', '36.62']
['AMZN', 'Nov 1 2000', '24.69']
['AMZN', 'Dec 1 2000', '15.56']
['AMZN', 'Jan 1 2001', '17.31']
['AMZN', 'Feb 1 2001', '10.19']
['AMZN', 'Mar 1 2001', '10.23']
['AMZN', 'Apr 1 2001', '15.78']
['AMZN', 'May 1 2001', '16.69']
['AMZN', 'Jun 1 2001', '14.15']
['AMZN', 'Jul 1 2001', '12.49']
['AMZN', 'Aug 1 2001', '8.94']
['AMZN', 'Sep 1 2001', '5.97']
['AMZN', 'Oct 1 2001', '6.98']
['AMZN', 'Nov 1 2001', '11.32']
['AMZN', 'Dec 1 2001', '10.82']
['AMZN', 'Jan 1 2002', '14.19']
['AMZN', 'Feb 1 2002', '14.1']
['AMZN', 'Mar 1 2002', '14.3']
['AMZN', 'Apr 1 2002', '16.69']
['AMZN', 'May 1 2002', '18.23']
['AMZN', 'Jun 1 2002', '16.25']
['AMZN', 'Jul 1 2002', '14.45']
['AMZN', 'Aug 1 2002', '14.94']
['AMZN', 'Sep 1 2002', '15.93']
['AMZN', 'Oct 1 2002', '19.36']
['AMZN', 'Nov 1 2002', '23.35']
['AMZN', 'Dec 1 2002', '18.89']
['AMZN', 'Jan 1 2003', '21.85']
['AMZN', 'Feb 1 2003', '22.01']
['AMZN', 'Mar 1 2003', '26.03']
['AMZN', 'Apr 1 2003', '28.69']
['AMZN', 'May 1 2003', '35.89']
['AMZN', 'Jun 1 2003', '36.32']
['AMZN', 'Jul 1 2003', '41.64']
['AMZN', 'Aug 1 2003', '46.32']
['AMZN', 'Sep 1 2003', '48.43']
['AMZN', 'Oct 1 2003', '54.43']
['AMZN', 'Nov 1 2003', '53.97']
['AMZN', 'Dec 1 2003', '52.62']
['AMZN', 'Jan 1 2004', '50.4']
['AMZN', 'Feb 1 2004', '43.01']
['AMZN', 'Mar 1 2004', '43.28']
['AMZN', 'Apr 1 2004', '43.6']
['AMZN', 'May 1 2004', '48.5']
['AMZN', 'Jun 1 2004', '54.4']
['AMZN', 'Jul 1 2004', '38.92']
['AMZN', 'Aug 1 2004', '38.14']
['AMZN', 'Sep 1 2004', '40.86']
['AMZN', 'Oct 1 2004', '34.13']
['AMZN', 'Nov 1 2004', '39.68']
['AMZN', 'Dec 1 2004', '44.29']
['AMZN', 'Jan 1 2005', '43.22']
['AMZN', 'Feb 1 2005', '35.18']
['AMZN', 'Mar 1 2005', '34.27']
['AMZN', 'Apr 1 2005', '32.36']
['AMZN', 'May 1 2005', '35.51']
['AMZN', 'Jun 1 2005', '33.09']
['AMZN', 'Jul 1 2005', '45.15']
['AMZN', 'Aug 1 2005', '42.7']
['AMZN', 'Sep 1 2005', '45.3']
['AMZN', 'Oct 1 2005', '39.86']
['AMZN', 'Nov 1 2005', '48.46']
['AMZN', 'Dec 1 2005', '47.15']
['AMZN', 'Jan 1 2006', '44.82']
['AMZN', 'Feb 1 2006', '37.44']
['AMZN', 'Mar 1 2006', '36.53']
['AMZN', 'Apr 1 2006', '35.21']
['AMZN', 'May 1 2006', '34.61']
['AMZN', 'Jun 1 2006', '38.68']
['AMZN', 'Jul 1 2006', '26.89']
['AMZN', 'Aug 1 2006', '30.83']
['AMZN', 'Sep 1 2006', '32.12']
['AMZN', 'Oct 1 2006', '38.09']
['AMZN', 'Nov 1 2006', '40.34']
['AMZN', 'Dec 1 2006', '39.46']
['AMZN', 'Jan 1 2007', '37.67']
['AMZN', 'Feb 1 2007', '39.14']
['AMZN', 'Mar 1 2007', '39.79']
['AMZN', 'Apr 1 2007', '61.33']
['AMZN', 'May 1 2007', '69.14']
['AMZN', 'Jun 1 2007', '68.41']
['AMZN', 'Jul 1 2007', '78.54']
['AMZN', 'Aug 1 2007', '79.91']
['AMZN', 'Sep 1 2007', '93.15']
['AMZN', 'Oct 1 2007', '89.15']
['AMZN', 'Nov 1 2007', '90.56']
['AMZN', 'Dec 1 2007', '92.64']
['AMZN', 'Jan 1 2008', '77.7']
['AMZN', 'Feb 1 2008', '64.47']
['AMZN', 'Mar 1 2008', '71.3']
['AMZN', 'Apr 1 2008', '78.63']
['AMZN', 'May 1 2008', '81.62']
['AMZN', 'Jun 1 2008', '73.33']
['AMZN', 'Jul 1 2008', '76.34']
['AMZN', 'Aug 1 2008', '80.81']
['AMZN', 'Sep 1 2008', '72.76']
['AMZN', 'Oct 1 2008', '57.24']
['AMZN', 'Nov 1 2008', '42.7']
['AMZN', 'Dec 1 2008', '51.28']
['AMZN', 'Jan 1 2009', '58.82']
['AMZN', 'Feb 1 2009', '64.79']
['AMZN', 'Mar 1 2009', '73.44']
['AMZN', 'Apr 1 2009', '80.52']
['AMZN', 'May 1 2009', '77.99']
['AMZN', 'Jun 1 2009', '83.66']
['AMZN', 'Jul 1 2009', '85.76']
['AMZN', 'Aug 1 2009', '81.19']
['AMZN', 'Sep 1 2009', '93.36']
['AMZN', 'Oct 1 2009', '118.81']
['AMZN', 'Nov 1 2009', '135.91']
['AMZN', 'Dec 1 2009', '134.52']
['AMZN', 'Jan 1 2010', '125.41']
['AMZN', 'Feb 1 2010', '118.4']
['AMZN', 'Mar 1 2010', '128.82']
['IBM', 'Jan 1 2000', '100.52']
['IBM', 'Feb 1 2000', '92.11']
['IBM', 'Mar 1 2000', '106.11']
['IBM', 'Apr 1 2000', '99.95']
['IBM', 'May 1 2000', '96.31']
['IBM', 'Jun 1 2000', '98.33']
['IBM', 'Jul 1 2000', '100.74']
['IBM', 'Aug 1 2000', '118.62']
['IBM', 'Sep 1 2000', '101.19']
['IBM', 'Oct 1 2000', '88.5']
['IBM', 'Nov 1 2000', '84.12']
['IBM', 'Dec 1 2000', '76.47']
['IBM', 'Jan 1 2001', '100.76']
['IBM', 'Feb 1 2001', '89.98']
['IBM', 'Mar 1 2001', '86.63']
['IBM', 'Apr 1 2001', '103.7']
['IBM', 'May 1 2001', '100.82']
['IBM', 'Jun 1 2001', '102.35']
['IBM', 'Jul 1 2001', '94.87']
['IBM', 'Aug 1 2001', '90.25']
['IBM', 'Sep 1 2001', '82.82']
['IBM', 'Oct 1 2001', '97.58']
['IBM', 'Nov 1 2001', '104.5']
['IBM', 'Dec 1 2001', '109.36']
['IBM', 'Jan 1 2002', '97.54']
['IBM', 'Feb 1 2002', '88.82']
['IBM', 'Mar 1 2002', '94.15']
['IBM', 'Apr 1 2002', '75.82']
['IBM', 'May 1 2002', '72.97']
['IBM', 'Jun 1 2002', '65.31']
['IBM', 'Jul 1 2002', '63.86']
['IBM', 'Aug 1 2002', '68.52']
['IBM', 'Sep 1 2002', '53.01']
['IBM', 'Oct 1 2002', '71.76']
['IBM', 'Nov 1 2002', '79.16']
['IBM', 'Dec 1 2002', '70.58']
['IBM', 'Jan 1 2003', '71.22']
['IBM', 'Feb 1 2003', '71.13']
['IBM', 'Mar 1 2003', '71.57']
['IBM', 'Apr 1 2003', '77.47']
['IBM', 'May 1 2003', '80.48']
['IBM', 'Jun 1 2003', '75.42']
['IBM', 'Jul 1 2003', '74.28']
['IBM', 'Aug 1 2003', '75.12']
['IBM', 'Sep 1 2003', '80.91']
['IBM', 'Oct 1 2003', '81.96']
['IBM', 'Nov 1 2003', '83.08']
['IBM', 'Dec 1 2003', '85.05']
['IBM', 'Jan 1 2004', '91.06']
['IBM', 'Feb 1 2004', '88.7']
['IBM', 'Mar 1 2004', '84.41']
['IBM', 'Apr 1 2004', '81.04']
['IBM', 'May 1 2004', '81.59']
['IBM', 'Jun 1 2004', '81.19']
['IBM', 'Jul 1 2004', '80.19']
['IBM', 'Aug 1 2004', '78.17']
['IBM', 'Sep 1 2004', '79.13']
['IBM', 'Oct 1 2004', '82.84']
['IBM', 'Nov 1 2004', '87.15']
['IBM', 'Dec 1 2004', '91.16']
['IBM', 'Jan 1 2005', '86.39']
['IBM', 'Feb 1 2005', '85.78']
['IBM', 'Mar 1 2005', '84.66']
['IBM', 'Apr 1 2005', '70.77']
['IBM', 'May 1 2005', '70.18']
['IBM', 'Jun 1 2005', '68.93']
['IBM', 'Jul 1 2005', '77.53']
['IBM', 'Aug 1 2005', '75.07']
['IBM', 'Sep 1 2005', '74.7']
['IBM', 'Oct 1 2005', '76.25']
['IBM', 'Nov 1 2005', '82.98']
['IBM', 'Dec 1 2005', '76.73']
['IBM', 'Jan 1 2006', '75.89']
['IBM', 'Feb 1 2006', '75.09']
['IBM', 'Mar 1 2006', '77.17']
['IBM', 'Apr 1 2006', '77.05']
['IBM', 'May 1 2006', '75.04']
['IBM', 'Jun 1 2006', '72.15']
['IBM', 'Jul 1 2006', '72.7']
['IBM', 'Aug 1 2006', '76.35']
['IBM', 'Sep 1 2006', '77.26']
['IBM', 'Oct 1 2006', '87.06']
['IBM', 'Nov 1 2006', '86.95']
['IBM', 'Dec 1 2006', '91.9']
['IBM', 'Jan 1 2007', '93.79']
['IBM', 'Feb 1 2007', '88.18']
['IBM', 'Mar 1 2007', '89.44']
['IBM', 'Apr 1 2007', '96.98']
['IBM', 'May 1 2007', '101.54']
['IBM', 'Jun 1 2007', '100.25']
['IBM', 'Jul 1 2007', '105.4']
['IBM', 'Aug 1 2007', '111.54']
['IBM', 'Sep 1 2007', '112.6']
['IBM', 'Oct 1 2007', '111']
['IBM', 'Nov 1 2007', '100.9']
['IBM', 'Dec 1 2007', '103.7']
['IBM', 'Jan 1 2008', '102.75']
['IBM', 'Feb 1 2008', '109.64']
['IBM', 'Mar 1 2008', '110.87']
['IBM', 'Apr 1 2008', '116.23']
['IBM', 'May 1 2008', '125.14']
['IBM', 'Jun 1 2008', '114.6']
['IBM', 'Jul 1 2008', '123.74']
['IBM', 'Aug 1 2008', '118.16']
['IBM', 'Sep 1 2008', '113.53']
['IBM', 'Oct 1 2008', '90.24']
['IBM', 'Nov 1 2008', '79.65']
['IBM', 'Dec 1 2008', '82.15']
['IBM', 'Jan 1 2009', '89.46']
['IBM', 'Feb 1 2009', '90.32']
['IBM', 'Mar 1 2009', '95.09']
['IBM', 'Apr 1 2009', '101.29']
['IBM', 'May 1 2009', '104.85']
['IBM', 'Jun 1 2009', '103.01']
['IBM', 'Jul 1 2009', '116.34']
['IBM', 'Aug 1 2009', '117']
['IBM', 'Sep 1 2009', '118.55']
['IBM', 'Oct 1 2009', '119.54']
['IBM', 'Nov 1 2009', '125.79']
['IBM', 'Dec 1 2009', '130.32']
['IBM', 'Jan 1 2010', '121.85']
['IBM', 'Feb 1 2010', '127.16']
['IBM', 'Mar 1 2010', '125.55']
['GOOG', 'Aug 1 2004', '102.37']
['GOOG', 'Sep 1 2004', '129.6']
['GOOG', 'Oct 1 2004', '190.64']
['GOOG', 'Nov 1 2004', '181.98']
['GOOG', 'Dec 1 2004', '192.79']
['GOOG', 'Jan 1 2005', '195.62']
['GOOG', 'Feb 1 2005', '187.99']
['GOOG', 'Mar 1 2005', '180.51']
['GOOG', 'Apr 1 2005', '220']
['GOOG', 'May 1 2005', '277.27']
['GOOG', 'Jun 1 2005', '294.15']
['GOOG', 'Jul 1 2005', '287.76']
['GOOG', 'Aug 1 2005', '286']
['GOOG', 'Sep 1 2005', '316.46']
['GOOG', 'Oct 1 2005', '372.14']
['GOOG', 'Nov 1 2005', '404.91']
['GOOG', 'Dec 1 2005', '414.86']
['GOOG', 'Jan 1 2006', '432.66']
['GOOG', 'Feb 1 2006', '362.62']
['GOOG', 'Mar 1 2006', '390']
['GOOG', 'Apr 1 2006', '417.94']
['GOOG', 'May 1 2006', '371.82']
['GOOG', 'Jun 1 2006', '419.33']
['GOOG', 'Jul 1 2006', '386.6']
['GOOG', 'Aug 1 2006', '378.53']
['GOOG', 'Sep 1 2006', '401.9']
['GOOG', 'Oct 1 2006', '476.39']
['GOOG', 'Nov 1 2006', '484.81']
['GOOG', 'Dec 1 2006', '460.48']
['GOOG', 'Jan 1 2007', '501.5']
['GOOG', 'Feb 1 2007', '449.45']
['GOOG', 'Mar 1 2007', '458.16']
['GOOG', 'Apr 1 2007', '471.38']
['GOOG', 'May 1 2007', '497.91']
['GOOG', 'Jun 1 2007', '522.7']
['GOOG', 'Jul 1 2007', '510']
['GOOG', 'Aug 1 2007', '515.25']
['GOOG', 'Sep 1 2007', '567.27']
['GOOG', 'Oct 1 2007', '707']
['GOOG', 'Nov 1 2007', '693']
['GOOG', 'Dec 1 2007', '691.48']
['GOOG', 'Jan 1 2008', '564.3']
['GOOG', 'Feb 1 2008', '471.18']
['GOOG', 'Mar 1 2008', '440.47']
['GOOG', 'Apr 1 2008', '574.29']
['GOOG', 'May 1 2008', '585.8']
['GOOG', 'Jun 1 2008', '526.42']
['GOOG', 'Jul 1 2008', '473.75']
['GOOG', 'Aug 1 2008', '463.29']
['GOOG', 'Sep 1 2008', '400.52']
['GOOG', 'Oct 1 2008', '359.36']
['GOOG', 'Nov 1 2008', '292.96']
['GOOG', 'Dec 1 2008', '307.65']
['GOOG', 'Jan 1 2009', '338.53']
['GOOG', 'Feb 1 2009', '337.99']
['GOOG', 'Mar 1 2009', '348.06']
['GOOG', 'Apr 1 2009', '395.97']
['GOOG', 'May 1 2009', '417.23']
['GOOG', 'Jun 1 2009', '421.59']
['GOOG', 'Jul 1 2009', '443.05']
['GOOG', 'Aug 1 2009', '461.67']
['GOOG', 'Sep 1 2009', '495.85']
['GOOG', 'Oct 1 2009', '536.12']
['GOOG', 'Nov 1 2009', '583']
['GOOG', 'Dec 1 2009', '619.98']
['GOOG', 'Jan 1 2010', '529.94']
['GOOG', 'Feb 1 2010', '526.8']
['GOOG', 'Mar 1 2010', '560.19']
['AAPL', 'Jan 1 2000', '25.94']
['AAPL', 'Feb 1 2000', '28.66']
['AAPL', 'Mar 1 2000', '33.95']
['AAPL', 'Apr 1 2000', '31.01']
['AAPL', 'May 1 2000', '21']
['AAPL', 'Jun 1 2000', '26.19']
['AAPL', 'Jul 1 2000', '25.41']
['AAPL', 'Aug 1 2000', '30.47']
['AAPL', 'Sep 1 2000', '12.88']
['AAPL', 'Oct 1 2000', '9.78']
['AAPL', 'Nov 1 2000', '8.25']
['AAPL', 'Dec 1 2000', '7.44']
['AAPL', 'Jan 1 2001', '10.81']
['AAPL', 'Feb 1 2001', '9.12']
['AAPL', 'Mar 1 2001', '11.03']
['AAPL', 'Apr 1 2001', '12.74']
['AAPL', 'May 1 2001', '9.98']
['AAPL', 'Jun 1 2001', '11.62']
['AAPL', 'Jul 1 2001', '9.4']
['AAPL', 'Aug 1 2001', '9.27']
['AAPL', 'Sep 1 2001', '7.76']
['AAPL', 'Oct 1 2001', '8.78']
['AAPL', 'Nov 1 2001', '10.65']
['AAPL', 'Dec 1 2001', '10.95']
['AAPL', 'Jan 1 2002', '12.36']
['AAPL', 'Feb 1 2002', '10.85']
['AAPL', 'Mar 1 2002', '11.84']
['AAPL', 'Apr 1 2002', '12.14']
['AAPL', 'May 1 2002', '11.65']
['AAPL', 'Jun 1 2002', '8.86']
['AAPL', 'Jul 1 2002', '7.63']
['AAPL', 'Aug 1 2002', '7.38']
['AAPL', 'Sep 1 2002', '7.25']
['AAPL', 'Oct 1 2002', '8.03']
['AAPL', 'Nov 1 2002', '7.75']
['AAPL', 'Dec 1 2002', '7.16']
['AAPL', 'Jan 1 2003', '7.18']
['AAPL', 'Feb 1 2003', '7.51']
['AAPL', 'Mar 1 2003', '7.07']
['AAPL', 'Apr 1 2003', '7.11']
['AAPL', 'May 1 2003', '8.98']
['AAPL', 'Jun 1 2003', '9.53']
['AAPL', 'Jul 1 2003', '10.54']
['AAPL', 'Aug 1 2003', '11.31']
['AAPL', 'Sep 1 2003', '10.36']
['AAPL', 'Oct 1 2003', '11.44']
['AAPL', 'Nov 1 2003', '10.45']
['AAPL', 'Dec 1 2003', '10.69']
['AAPL', 'Jan 1 2004', '11.28']
['AAPL', 'Feb 1 2004', '11.96']
['AAPL', 'Mar 1 2004', '13.52']
['AAPL', 'Apr 1 2004', '12.89']
['AAPL', 'May 1 2004', '14.03']
['AAPL', 'Jun 1 2004', '16.27']
['AAPL', 'Jul 1 2004', '16.17']
['AAPL', 'Aug 1 2004', '17.25']
['AAPL', 'Sep 1 2004', '19.38']
['AAPL', 'Oct 1 2004', '26.2']
['AAPL', 'Nov 1 2004', '33.53']
['AAPL', 'Dec 1 2004', '32.2']
['AAPL', 'Jan 1 2005', '38.45']
['AAPL', 'Feb 1 2005', '44.86']
['AAPL', 'Mar 1 2005', '41.67']
['AAPL', 'Apr 1 2005', '36.06']
['AAPL', 'May 1 2005', '39.76']
['AAPL', 'Jun 1 2005', '36.81']
['AAPL', 'Jul 1 2005', '42.65']
['AAPL', 'Aug 1 2005', '46.89']
['AAPL', 'Sep 1 2005', '53.61']
['AAPL', 'Oct 1 2005', '57.59']
['AAPL', 'Nov 1 2005', '67.82']
['AAPL', 'Dec 1 2005', '71.89']
['AAPL', 'Jan 1 2006', '75.51']
['AAPL', 'Feb 1 2006', '68.49']
['AAPL', 'Mar 1 2006', '62.72']
['AAPL', 'Apr 1 2006', '70.39']
['AAPL', 'May 1 2006', '59.77']
['AAPL', 'Jun 1 2006', '57.27']
['AAPL', 'Jul 1 2006', '67.96']
['AAPL', 'Aug 1 2006', '67.85']
['AAPL', 'Sep 1 2006', '76.98']
['AAPL', 'Oct 1 2006', '81.08']
['AAPL', 'Nov 1 2006', '91.66']
['AAPL', 'Dec 1 2006', '84.84']
['AAPL', 'Jan 1 2007', '85.73']
['AAPL', 'Feb 1 2007', '84.61']
['AAPL', 'Mar 1 2007', '92.91']
['AAPL', 'Apr 1 2007', '99.8']
['AAPL', 'May 1 2007', '121.19']
['AAPL', 'Jun 1 2007', '122.04']
['AAPL', 'Jul 1 2007', '131.76']
['AAPL', 'Aug 1 2007', '138.48']
['AAPL', 'Sep 1 2007', '153.47']
['AAPL', 'Oct 1 2007', '189.95']
['AAPL', 'Nov 1 2007', '182.22']
['AAPL', 'Dec 1 2007', '198.08']
['AAPL', 'Jan 1 2008', '135.36']
['AAPL', 'Feb 1 2008', '125.02']
['AAPL', 'Mar 1 2008', '143.5']
['AAPL', 'Apr 1 2008', '173.95']
['AAPL', 'May 1 2008', '188.75']
['AAPL', 'Jun 1 2008', '167.44']
['AAPL', 'Jul 1 2008', '158.95']
['AAPL', 'Aug 1 2008', '169.53']
['AAPL', 'Sep 1 2008', '113.66']
['AAPL', 'Oct 1 2008', '107.59']
['AAPL', 'Nov 1 2008', '92.67']
['AAPL', 'Dec 1 2008', '85.35']
['AAPL', 'Jan 1 2009', '90.13']
['AAPL', 'Feb 1 2009', '89.31']
['AAPL', 'Mar 1 2009', '105.12']
['AAPL', 'Apr 1 2009', '125.83']
['AAPL', 'May 1 2009', '135.81']
['AAPL', 'Jun 1 2009', '142.43']
['AAPL', 'Jul 1 2009', '163.39']
['AAPL', 'Aug 1 2009', '168.21']
['AAPL', 'Sep 1 2009', '185.35']
['AAPL', 'Oct 1 2009', '188.5']
['AAPL', 'Nov 1 2009', '199.91']
['AAPL', 'Dec 1 2009', '210.73']
['AAPL', 'Jan 1 2010', '192.06']
['AAPL', 'Feb 1 2010', '204.62']
['AAPL', 'Mar 1 2010', '223.02']

In [ ]:
headers = ['Symbol', 'Price', 'Date', 'Time', 'Change', 'Volume']
rows = [{'Symbol':'AA', 'Price':39.48, 'Date':'6/11/2007',
              'Time':'9:36am', 'Change':-0.18, 'Volume':181800},
            {'Symbol':'AIG', 'Price': 71.38, 'Date':'6/11/2007',
              'Time':'9:36am', 'Change':-0.15, 'Volume': 195500},
            {'Symbol':'AXP', 'Price': 62.58, 'Date':'6/11/2007',
              'Time':'9:36am', 'Change':-0.46, 'Volume': 935000},
            ]
with open('/Users/harishkaparwan/Developer/Github/GettingStartedWithPython/stocks1.csv','w') as f: 
        f_csv = csv.DictWriter(f, headers) 
        f_csv.writeheader() 
        f_csv.writerows(rows)

In [ ]:
import json
data = {
       'name' : 'ACME',
       'shares' : 100,
       'price' : 542.23
}
json_str = json.dumps(data)
#print(json_str)

# Writing JSON data
with open('/Users/harishkaparwan/Developer/Github/GettingStartedWithPython/data.json', 'w') as f: 
    json.dump(data, f)
# Reading data back
with open('/Users/harishkaparwan/Developer/Github/GettingStartedWithPython/data.json', 'r') as f: 
    data = json.load(f)
    print(data)

{'name': 'ACME', 'shares': 100, 'price': 542.23}